### ISSUE TITLE
Update Glide Version

### ISSUE THREAD

**Issue by ahmedjamshedlead** [meharbhutta/react-native-manage-wallpaper#1]
### Expected behaviour
This library should work with Latest Glide

### Actual behaviour
Glide version is deprecated

### Environment
- **React Native version*0.61*:
- **React Native platform + platform version**: Android 5.0, etc

### react-native-manage-wallpaper
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by meharbhutta** [comment]
Updated glide version in v2.0.0.
