### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.ManageWallpapers.setWallpaper')

### ISSUE THREAD

**Issue by NateyLB** [meharbhutta/react-native-manage-wallpaper#3]
### Steps to reproduce
1.NPM install 
2.Copy example use case
3.set onPress to use _setWallpaper

### Expected behaviour
The app should let user set wallpaper

### Actual behaviour
We get TypeError: null is not an object (evaluating '_reactNative.NativeModules.ManageWallpapers.setWallpaper')
Error

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 13.4 iPhone 11

### react-native-manage-wallpaper
**Version**: npm version or "master"
6.14.4

### Link to repo (highly encouraged)
https://github.com/NateyLB/randomDog

![image](https://user-images.githubusercontent.com/38302941/79672616-985d2d00-8188-11ea-9b6d-5a4ad1c79391.png)

**Comment by dev-ramij** [comment]
I have same issue please provide solution

**Comment by iyansr** [comment]
can you console your `props.dog.url` ?

**Comment by adityakmr7** [comment]
I am having same issue I tried to implement this to my expo app.

**Comment by dev-ramij** [comment]
Guys it will not work on expo app. Because setting wallpaper is done by native modules. So try to eject your expo project to react-native app. It will work 😊

**Comment by meharbhutta** [comment]
In one word it is not possible. In Apple devices, There is no provision for the change of iOS Screen wallpaper programmatically. The user has to do that manually through the settings or photos app.[See this](https://stackoverflow.com/questions/56112014/can-i-change-ios-screen-wallpaper-programmatically-in-swift-5-and-ios-12)
