### ISSUE TITLE
gradle build failed 

### ISSUE THREAD

**Issue by mixmaker** [meharbhutta/react-native-manage-wallpaper#7]
### Steps to reproduce
1. install the package using `yarn add react-native-manage-wallpaper`
2. start the metro server using `npx react-native run-android`

### Expected behaviour
App should be compiled correctly

### Actual behaviour
gradle fails to compile the pakcage react-native-manage-wallpaper
`
1: Task failed with an exception.
-----------
* Where:
Build file '...\{appname}\node_modules\react-native-manage-wallpaper\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':react-native-manage-wallpaper'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-manage-wallpaper'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
`
### Environment
- **React Native version**: 0.68.2
- **React Native platform + platform version**: Android 11.0,

### react-native-manage-wallpaper
**Version**: 1.1.2

### Link to repo (highly encouraged)
https://github.com/

**Comment by usamabinishaq** [comment]
Same Issue
did you find any solution for it

**Comment by usamabinishaq** [comment]
@mixmaker

**Comment by mahmoudafer** [comment]
facing the same issue, seems it's because gradle 7.x deprecated maven for maven-publish

**Comment by mdalishanali** [comment]
same here..

**Comment by DeveloperHarshPatel** [comment]
Getting same issue. Any solution ?

**Comment by mdalishanali** [comment]
@DeveloperHarshPatel Bro are you creating wallpaper app?😁

**Comment by meharbhutta** [comment]
Issue resolved in latest build v1.2.1
