### ISSUE TITLE
Gradle Build Failed on React native 0.69

### ISSUE THREAD

**Issue by ghost** [meharbhutta/react-native-manage-wallpaper#8]
While building Gradle Build Failed with the error of min SDK Version error

**Comment by natanfeitosa** [comment]
I think this project is abandoned. You can use [this lib](https://github.com/natanfeitosa/rn-wallpapers) that was released a few days ago

**Comment by meharbhutta** [comment]
A similar issue was resolved. [See this](https://github.com/meharbhutta/react-native-manage-wallpaper/issues/7)
